### ISSUE TITLE
lein template compilation issue on Windows due to git symlinks

### ISSUE THREAD

**Issue by markokocic** [kit-clj/kit#38] opened 2022-03-09 16:34 UTC
When I build and install `lein-template` on Windows and attempt to generate any project locally, version information for libraries is empty for any kit library in `deps.edn` file.

It appears that behaviour is broken due to introduction of symlinked `versions.edn` in 1bb1fbcebc8172831dbbd16e545288d4d9b7b4d9
Apparently `git` on Windows doesn't support symlinks, instead it generates a file which contains a path to the original file.

There are few possible solutions:
1. move `versions.edn` to `lein-template` project. Reference that file from the main `build.clj` script.
2. keep two duplicate versions of `versions.edn` in project root directory and in libs/lein-template
3. update build script for lein-template to include `versions.edn` from the root folder when building jar.

I would prefer solution 1. since 2. adds duplication and 3 is ugly.

**Comment by yogthos** [comment] 2022-03-09 19:29
The problem is that the file is used by all the libraries, so solution 3 would probably be the right way to go to make it build on windows.

**Comment by markokocic** [comment] 2022-03-09 19:41
I found the only reference in build.clj where it’s used during the build itself, no runtime reference. 

After applying the referenced pull request I was able to build all libs and project got generated properly.

**Comment by yogthos** [comment] 2022-03-09 22:24
We might be ok then, if everything looks good to @nikolap I'm ok get the PR merged in.

**Comment by nikolap** [comment] 2022-03-10 10:08
Yeah this is okay if build somehow works on Windows with it

**Closed** 2022-03-10 10:09 UTC
